### ISSUE TITLE
Problems with the local network interface and DHCP

### ISSUE THREAD

**Issue by PLCHome** [ioBroker/ioBroker.knx#107]
The network interface and the IP are saved in the field Local network interface.
Since I use the ioBroker in a Docker with DHCP, the IP address changes on every rebuild. In this case, the instance of the adapter no longer starts.
It would be nice if the network interface was saved without an IP address in the config and the IP address was determined when the instance was started.

Version: 1.0.41

**Comment by PLCHome** [comment]
If you leave the network interface empty, this also works with DHCP. 
**The problem is that once you have selected an entry there you can no longer delete it.**
Can someone add an empty entry to the selection list?

![image](https://user-images.githubusercontent.com/29116097/88183125-58975d00-cc31-11ea-86d6-1248fb9d4e85.png)

**Comment by RESDE** [comment]
Hi, is it not possibe under your DHCP "Master" to set the IOBroker with a fixed IP address instead of DHCP mode? Changing DHCP addresses are sometimes not everywhere the best choice. I had it in my early days of IOBroker but decided to switch to static IP address mode which eases a lot the programming inside other iobroker adapters....
Cheers
Reiner

**Comment by PLCHome** [comment]
> Hi, is it not possibe under your DHCP "Master" to set the IOBroker with a fixed IP address instead of DHCP mode? 

I have now found a solution.

Before that I just reinstalled the adapter and didn't select anything. Then it also worked with DHCP. Maybe you can add the empty selection again.

In the old interface, the selection of the empty address is still available in the interface.
