### ISSUE TITLE
Verbindungsabbrüche 

### ISSUE THREAD

**Issue by AndyBauer119** [ioBroker/ioBroker.knx#153]
Hallo,

nachdem der KNX Adapter bei mir seit einiger Zeit nicht mehr so zuverlässig funktioniert, habe ich versucht, die Ursache dafür raus zu finden. Durch Testen der unterschiedlichen Versionen sieht es bei mir so aus, dass die Version 1.0.35 die letzte für mich funktionierende Version darstellt. Die Versionen darüber bis inklusive 1.0.44 haben führen bei mir zu laufenden Verbindungsabbrüchen zum IP Interface, welche ich mir nicht erklären kann.

Danke und SG
Andy

2021-03-11 17:48:28.293 - info: knx.0 (1429) STATE_NOT_CONNECTED : Try to connect / reconnect : STATE_READY(7) to STATE_NOT_CONNECTED(0).
2021-03-11 17:48:28.299 - info: knx.0 (1429) STATE_NOT_CONNECTED : Stop connection : STATE_DISCONNECT_REQUEST(15) to STATE_NOT_CONNECTED(0).
2021-03-11 17:48:28.304 - info: knx.0 (1429) STATE_NOT_CONNECTED : Stop connection : STATE_DISCONNECT_RESPONSE(16) to STATE_NOT_CONNECTED(0).
2021-03-11 17:48:30.295 - info: knx.0 (1429) Using UDP with local IP: 10.0.0.101
2021-03-11 17:48:30.297 - info: knx.0 (1429) Connected - local UDP Server listening on 10.0.0.101:33353
2021-03-11 17:57:10.782 - info: knx.0 (1429) STATE_NOT_CONNECTED : Try to connect / reconnect : STATE_READY(7) to STATE_NOT_CONNECTED(0).
2021-03-11 17:57:10.786 - info: knx.0 (1429) STATE_NOT_CONNECTED : Stop connection : STATE_DISCONNECT_REQUEST(15) to STATE_NOT_CONNECTED(0).
2021-03-11 17:57:10.790 - info: knx.0 (1429) STATE_NOT_CONNECTED : Stop connection : STATE_DISCONNECT_RESPONSE(16) to STATE_NOT_CONNECTED(0).
2021-03-11 17:57:12.784 - info: knx.0 (1429) Using UDP with local IP: 10.0.0.101
2021-03-11 17:57:12.786 - info: knx.0 (1429) Connected - local UDP Server listening on 10.0.0.101:60572
2021-03-11 17:59:53.779 - info: knx.0 (1429) STATE_NOT_CONNECTED : Try to connect / reconnect : STATE_READY(7) to STATE_NOT_CONNECTED(0).
2021-03-11 17:59:53.783 - info: knx.0 (1429) STATE_NOT_CONNECTED : Stop connection : STATE_DISCONNECT_REQUEST(15) to STATE_NOT_CONNECTED(0).
2021-03-11 17:59:53.787 - info: knx.0 (1429) STATE_NOT_CONNECTED : Stop connection : STATE_DISCONNECT_RESPONSE(16) to STATE_NOT_CONNECTED(0).
2021-03-11 17:59:55.780 - info: knx.0 (1429) Using UDP with local IP: 10.0.0.101
2021-03-11 17:59:55.782 - info: knx.0 (1429) Connected - local UDP Server listening on 10.0.0.101:34998
2021-03-11 18:04:16.580 - info: knx.0 (1429) STATE_NOT_CONNECTED : Try to connect / reconnect : STATE_READY(7) to STATE_NOT_CONNECTED(0).
2021-03-11 18:04:16.584 - info: knx.0 (1429) STATE_NOT_CONNECTED : Stop connection : STATE_DISCONNECT_REQUEST(15) to STATE_NOT_CONNECTED(0).
2021-03-11 18:04:16.587 - info: knx.0 (1429) STATE_NOT_CONNECTED : Stop connection : STATE_DISCONNECT_RESPONSE(16) to STATE_NOT_CONNECTED(0).
2021-03-11 18:04:18.580 - info: knx.0 (1429) Using UDP with local IP: 10.0.0.101
2021-03-11 18:04:18.583 - info: knx.0 (1429) Connected - local UDP Server listening on 10.0.0.101:54966
2021-03-11 18:05:53.580 - info: knx.0 (1429) STATE_NOT_CONNECTED : Try to connect / reconnect : STATE_READY(7) to STATE_NOT_CONNECTED(0).
2021-03-11 18:05:53.584 - info: knx.0 (1429) STATE_NOT_CONNECTED : Stop connection : STATE_DISCONNECT_REQUEST(15) to STATE_NOT_CONNECTED(0).
2021-03-11 18:05:53.590 - info: knx.0 (1429) STATE_NOT_CONNECTED : Stop connection : STATE_DISCONNECT_RESPONSE(16) to STATE_NOT_CONNECTED(0).
2021-03-11 18:05:55.581 - info: knx.0 (1429) Using UDP with local IP: 10.0.0.101
2021-03-11 18:05:55.583 - info: knx.0 (1429) Connected - local UDP Server listening on 10.0.0.101:38624

**Comment by unstressable** [comment]
Hatte das gleiche Problem und ebenfalls dowgraded. Hab jetzt 1.0.20, die läuft super!

**Comment by chefkoch009** [comment]
Der Adapter prüft periodisch, ob die Verbindung noch besteht. Also wenn eine gewisse Zeit kein KNX Paket empfangen wurde, dann wird ein CON_STATE_REQ geschickt. Je nach Antwort versucht der Adapter die Verbindung wieder zu beleben. Die obige Meldung ist also an dieser Stelle leider etwas irreführend, das gebe ich zu.

**Comment by AndyBauer119** [comment]
Danke für die Info. Ich hatte das Problem, dass zwischeinzeitlich immer wieder mal keine KNX-Funktionen über ioBroker ausgeführt werden konnten. In diesem Zeitbereich gab es dann auch die entsprechenden Fehlermeldungen im LOG. Die Version 1.0.35 läuft bei mir seit mittlerweile 2 Wochen einwandfrei. Soll ich testhalber versuchen, wie sich bei mir die aktuelle Version verhält, wenn ich dabei zusätzlich zyklisch Werte auf den Bus sende?

**Comment by RESDE** [comment]
@AndyBauer119 sehr schön dass Du Hilfe anbietest, die ist jedoch nicht sos ehr notwendig: der KNX Adapter kommt mit regelmäßig zyklisch gesendeten Werten bestens zurecht. Bedenke bitte Du bist Dich nicht der 1. User des Adapters... ;-)

**Comment by AndyBauer119** [comment]
:-)

**Comment by Tomtheripper** [comment]
Hallo chefkoch009,

d.h. wir können den Fehlereintrag im Log ignorieren?
(bei den vorherigen KNX.-Versionen gab es den Eintrag nicht)

Bytheway: Mega "Danke" an Dich, chefkoch009 !!!

Der Vollständigkeit halber anbei mein Log, man sieht, alle zwei Minuten ein "Verbindungsabbruch":
[iobroker.2021-04-06.log](https://github.com/ioBroker/ioBroker.knx/files/6266392/iobroker.2021-04-06.log)

Ich lehn' mich jetzt mal weit aus dem Fenster:
Tatsächlich habe ich das Gefühl, dass das reale Verbindungsabbrüche sind, da die betroffene Peripherie (bei mir: Sprachausgabe von KNX-Zuständen durch Alexa) nicht immer funktioniert. Und das seit den Updates (v44/v45).

Dieses Problem wurde Ende 2019 schonmal eroiert - und auch gelöst -, Stichwort "ElabNET Timberwolf-Server".

Beste Grüße
Thomas

**Comment by MiCon72** [comment]
Ich habe auch mit Verbindungsabbrüchen zu kämpfen. Der Fehler entspricht genau dem hier geschilderten Verhalten. Ich hatte aber auch mal die Debug-Stufe hochgestellt und dabei festgestellt, dass es zumindest bei mir vielleicht nicht am KNX-Adapter liegt. Der Adapter fragt ja regelmäßig entsprechend der KNX-Norm den Status mit einem  "State_connection_request"  ab. Mein Gateway (Wiregate) antwortet meistens auf diese Anfrage wie folgt:

Received CONNECTIONSTATE_RESPONSE : 06 10 02 08 00 08 02 00 192.168.178.32:3671 ChID : 2 SeqCntIN : 234 SeqCntOUT : 97 msgCode : [object Object]

Damit funktioniert auch alles vernünftig. Manchmal sendet mein Wiregate aber folgende Antwort:

Received CONNECTIONSTATE_RESPONSE : 06 10 02 08 00 08 02 15 192.168.178.32:3671 ChID : 2 SeqCntIN : 72 SeqCntOUT : 97 msgCode : [object Object]

Mit dieser Antwort kann der Adapter wohl nichts anfangen und beendet die Verbindung. Im Log sieht das dann so aus:

knx.0 (32461) STATE_DISCONNECT_REQUEST : no defined handling for transition from State: STATE_CONNECTION_STATE_RESPONSE(6) to STATE_DISCONNECT_REQUEST(15).
knx.0 (32461) Connection persists.....closing now
knx.0 (32461) ... not able to close connection, because already closed
knx.0 (32461) STATE_NOT_CONNECTED : Try to connect / reconnect : STATE_DISCONNECT_REQUEST(15) to STATE_NOT_CONNECTED(0).
knx.0 (32461) ...set STATE-NOT-CONNECTED
knx.0 (32461) Connection persists.....closing now
knx.0 (32461) ... not able to close connection, because already closed
knx.0 (32461) STATE_NOT_CONNECTED : Stop connection : STATE_NOT_CONNECTED(0) to STATE_NOT_CONNECTED(0).
knx.0 (32461) Using UDP with local IP: 192.168.178.162
knx.0 (32461) Event : UDP - listening
knx.0 (32461) Connected - local UDP Server listening on 192.168.178.162:38802

Weiter bin ich nicht gekommen. Insbesondere konnte ich nicht herausfinden, was der Status 15 vom Wiregate bedeutet. Wenn ich das in Erfahrung bringen könnte, würde man dem Problem wohl näher kommen.

Liebe Grüße

Michael

**Comment by unstressable** [comment]
Ich bin mittlerweile zurück auf die Version 1.0.20, die läuft viel stabiler. Um genau zu sein läuft diese perfekt.

**Comment by chefkoch009** [comment]
@MiCon72 Wenn die Kommunikation aufgebaut wird, dann wird eine  ChannelID ausgehandelt. In deinem Fall die 2. Wenn das zwischen den Komponenten geklärt ist, werden die eingehenden und ausgehenden Sequenzen mitgezählt. Wenn sich nun einer von Beiden verzählt, wird von der anderen Stelle dieses Paket ignoriert. STATE_DISCON_REQ ist dann quasi die Aufforderung, die Verbindung zu beenden. Und eine Transition von STATE_CONNECTION_STATE_RESPONSE(6) to STATE_DISCONNECT_REQUEST(15) ist nicht vorgesehen. Somit wird sofort die Verbindung beendet und neu aufgebaut.

**Comment by MiCon72** [comment]
@chefkoch009: Vielen Dank für die Erläuterung. Dann wird bei mir wohl vermutlich die Verbindung zwischen ioBroker und Wiregate nicht sehr stabil sein und es geht zwischendurch schon einmal ein Paket verloren. Vielleicht hängt das damit zusammen, dass ioBroker im Container auf einer Synology läuft. Ich habe hier noch einen RaspberryPi rumliegen. Ich werde ioBroker mal darauf installieren und dann schauen, wie es aussieht. Hoffentlich ist es dann weg. Oder meinst Du, der Zugang des Wiregate ist nicht stabil genug und ich sollte eine andere Schnittstelle anschaffen? Ich finde ioBroker an sich super, nur sollte so ein System schon stabil laufen. Ich gehe auch davon aus, dass er das grundsätzlich macht, sonst wären die Diskussionen hierüber sicherlich deutlich umfangreicher.

@AndyBauer119: Vielleicht könntest Du Deinen Debug-Level auch mal hochstellen und überprüfen, ob der Fehler bei Dir der gleiche ist. Dann könnte der Issue hier vielleicht bald auf erledigt gesetzt werden.

**Comment by MiCon72** [comment]
Ich habe zu Testzwecken ioBroker mal auf einer eigenen leistungsfähigen Maschine aufgesetzt, um nicht die Performance als Flaschenhals zu haben. Leider habe ich auch dort die Verbindungsabbrüche. Ich habe den Debug-Level mal noch weiter erhöht und es zeigt sich das gleiche Bild. Grundsätzlich treffen regelmäßig Telegramme ein (ca. 20-30 pro Minute) und es werden Telgramme auch gesendet. In unregelmäßigen Abständen von ca. 1-2 Minuten prüft ioBroker aber den Status der Verbindung. In ungefähr 50% der Fälle sieht die Prüfung wie folgt aus:

knx.0 (6844) checkConnectionState 192.168.178.32   State : true
knx.0 (6844) Send : conCheck Connection State Request :  06 10 02 07 00 10 01 00 08 01 c0 a8 b2 45 c2 7f        sent to 192.168.178.32:3671
knx.0 (6844) Change state from STATE_READY(7) to STATE_CONNECTION_STATE_REQUEST(5)
knx.0 (6844) Received CONNECTIONSTATE_RESPONSE :    06 10 02 08 00 08 01 00                                                              192.168.178.32:3671 ChID : 1 SeqCntIN : 63 SeqCntOUT : 0  msgCode : [object Object]
knx.0 (6844) Change state from STATE_CONNECTION_STATE_REQUEST(5) to STATE_CONNECTION_STATE_RESPONSE(6)
knx.0 (6844) Change state from STATE_CONNECTION_STATE_RESPONSE(6) to STATE_READY(7)

In den anderen 50% aber leider so:

knx.0 (6844) checkConnectionState 192.168.178.32   State : true
knx.0 (6844) Send : conCheck Connection State Request :  06 10 02 07 00 10 01 00 08 01 c0 a8 b2 45 c2 7f        sent to 192.168.178.32:3671
knx.0 (6844) Change state from STATE_READY(7) to STATE_CONNECTION_STATE_REQUEST(5)
knx.0 (6844) Received CONNECTIONSTATE_RESPONSE :    06 10 02 08 00 08 01 15                                                              192.168.178.32:3671 ChID : 1 SeqCntIN : 133 SeqCntOUT : 0  msgCode : [object Object]
knx.0 (6844) Change state from STATE_CONNECTION_STATE_REQUEST(5) to STATE_CONNECTION_STATE_RESPONSE(6)
knx.0 (6844) Change state from STATE_CONNECTION_STATE_RESPONSE(6) to STATE_DISCONNECT_REQUEST(15)
knx.0 (6844)  STATE_DISCONNECT_REQUEST : no defined handling for transition from State: STATE_CONNECTION_STATE_RESPONSE(6) to STATE_DISCONNECT_REQUEST(15).
knx.0 (6844) Change state from STATE_DISCONNECT_REQUEST(15) to STATE_NOT_CONNECTED(0)
knx.0 (6844)  Connection persists.....closing now
knx.0 (6844)  ... not able to close connection, because already closed
knx.0 (6844)  STATE_NOT_CONNECTED : Try to connect / reconnect :  STATE_DISCONNECT_REQUEST(15) to STATE_NOT_CONNECTED(0).
knx.0 (6844) ...set STATE-NOT-CONNECTED
knx.0 (6844) Change state from STATE_NOT_CONNECTED(0) to STATE_NOT_CONNECTED(0)
knx.0 (6844)  Connection persists.....closing now
knx.0 (6844)  ... not able to close connection, because already closed
knx.0 (6844)  STATE_NOT_CONNECTED : Stop connection :  STATE_NOT_CONNECTED(0) to STATE_NOT_CONNECTED(0).
knx.0 (6844) Using UDP with local IP: 192.168.178.69
knx.0 (6844) Change state from STATE_NOT_CONNECTED(0) to STATE_OPENING_PORT(1)
knx.0 (6844) Event : UDP - listening
knx.0 (6844) Change state from STATE_OPENING_PORT(1) to STATE_PORT_OPENED(2)
knx.0 (6844) Connected  - local UDP Server listening on 192.168.178.69:55108
knx.0 (6844) Send : UDP Connection Request :        06 10 02 05 00 1a 08 01 00 00 00 00 d7 44 08 01 c0 a8 b2 45 d7 44 04 04 02 00        sent to 192.168.178.32:3671
knx.0 (6844) Change state from STATE_PORT_OPENED(2) to STATE_CONNECT_REQUEST(3)
knx.0 (6844) Change state from STATE_CONNECT_REQUEST(3) to STATE_CONNECT_RESPONSE(4)
knx.0 (6844) Received  CONNECTION_RESPONSE : 06 10 02 06 00 14 01 00 08 01 00 00 00 00 00 00 04 04 00 00    GW-IP: 192.168.178.32:3671 -  ChannelID: 1 cnt IN/OUT: 0/0
knx.0 (6844) Change state from STATE_CONNECT_RESPONSE(4) to STATE_READY(7)

Die Anzahl der Pakete hat daher m. E. nichts mit dem Problem zu tun. Jeweils vor den Statusabfragen zeigt die Kommunikation m. E. keinerlei Auffälligkeiten. Hier mal das letzte Telegramm vor einer negativen Statusabfrage:

knx.0 (6844) ( 3.2 ) Received TUNNEL_REQUEST (WRITE - send ACK )         :    06 10 04 20 00 17 04 01 3a 00 29 00 bc d0 00 21 2f 01 03 00 80 54 a7   ChID: 1
knx.0 (6844) WRITE : mappedName : Helligkeit SÃ¼d    dest : 5/7/1  val: 21671   (DPT7.013) Helligkeit_SÃ¼d
knx.0 (6844) Change state from STATE_READY(7) to STATE_TUNNELLING_REQUEST(13)
knx.0 (6844) Change state from STATE_TUNNELLING_REQUEST(13) to STATE_TUNNELLING_ACK(14)
knx.0 (6844) =====> STATE_TUNNELING_ACK
knx.0 (6844) ( 4 ) Sending Tunnel_Request ACK  : 06 10 04 21 00 0a 04 01 3a 00   ChID : 1 SeqCntIN : 58 SeqCntOUT : 0 queue length : 0
knx.0 (6844) ( 4.b ) return to STATE_READY, processing : false
knx.0 (6844) Change state from STATE_TUNNELLING_ACK(14) to STATE_READY(7)

Die Abfrage des Status des Tunnels ist soweit ich recherchieren konnte notwendiger Bestandteil der KNX-Spezifikation. Diesen "Heartbeat" sendet auch der Adapter. Nur leider antwortet mein Gateway (Wiregate) scheinbar mal mit dem Status "0", was in Ordnung ist und der Adapter macht weiter, aber auch mal mit Status "15", was scheinbar nicht in Ordnung ist bzw. den Adapter zumindest dazu veranlasst, die Verbindung zu trennen.

Weiß denn jemand, was dieser Status "15" bedeutet? Das würde bei der Fehlersuche sicherlich helfen.

Vielen Dank!

**Comment by MiCon72** [comment]
Ich habe mittlerweile auch die Version 1.20 installiert. Dort werden die Heartbeats rechtzeitig gesendet und ich habe jetzt schon seit Stunden keinerlei Trennungen mehr.

**Comment by RESDE** [comment]
Es liegt wohl sehr stark an dem KNX Gateway, der nach Aushandlung der Verbindung mit dem KNX Adapter des IOBroker diesen dann nicht im KNX Protokoll festgelegten Zeitrahmen zu Ende kommuniziert. Daher beendet der KNX Adapter dann seinerseits die Verbindung, um für einen neuen Verbindungsaufbau nicht blockiert zu sein. Das soll technisch auch so sein, weil es das KNX Kommunikationsprotokoll so fordert.
Rückfrage: schaust Du selbst in der KNX Welt ebenfalls auf die Verbindungsabbrüche, die durch das Device Wiregate oder andere Devives verursachen? Ich meine nicht das ETS Monitoring, das die Software mitbringt, sondern eben auf der Ebene der Kommunikations-Verbindungen? Daher bitte mal den Blick vom Kommunikationstunnel in den Adapter die Augen wieder etwas abwenden statt seitenweise Protokolle hier einzustellen.
Bei mir und vielen anderen läuft der Adapter absolut stabil, verwendet werden aber doch eher stabile Gateway: der Gira X1 Server als IP Gateway werkelt in meine ETS Welt...und meine Abbrüche sind sehr überschaubar wenige...
Leider können wir hier im Forum keinen support für die Verbindungsabbrüche der diversen Gateways machen, das besser im KNX Forum platzieren oder so

**Comment by MiCon72** [comment]
Der Heartbeat wird aber doch vom Adapter gesendet und nicht vom Gateway (solange ich nicht hier einen grundlegenden Denkfehler habe und der Heartbeat vom Gateway gesendet wird), von daher verstehe ich nicht, warum das Gateway schuld sein soll, wenn der Heartbeat nicht innerhalb von 120 Sekunden gesendet wird. Das Gateway antwortet ja auch, allerdings mit der Nachricht, dass der Tunnel beim Gateway nicht mehr existent ist, weil der Heartbeat nicht innerhalb der vorgeschriebenen Zeit kam. Der Adapter erhält ja die Nachricht, dass der Tunnel nicht mehr steht und baut diesen dann intern ab und einen neuen wieder auf. Laut Protokolle ist es einfach nicht richtig, dass der Adapter die Verbindung abbaut, weil er keine  rechtzeitige Kommunikationsantwort vom Gateway erhält. Dann wäre da auch noch, dass mit der Version 1.20 das gleiche Gateway bis jetzt problemlos funktioniert. Das deutet für mich doch mehr auf ein Problem beim Adapter hin. 

In der KNX-Welt und mit dem am Wiregate-Gateway ebenfalls angeschlossenen Gira Homeserver hatte ich die letzte acht Jahre nicht einen feststellbaren Kommunikationsabbruch. Aufgrund der Problematik habe ich zwischenzeitlich auch mit Node Red etwas ausprobiert; auch dort gibt es keine Verbindungsabbrüche zum Gateway. Die Probleme habe ich nur mit dem KNX-Adapter in den neueren Versionen. Den KNX-Bus hatte ich auch schon einmal mit dem EIB-Doktor analysiert und konnte keine Fehler feststellen. Ich weiß aber auch nicht, was die Kommunikation auf dem KNX-Bus mit der IP-Verbindung zu tun haben soll. Gegenfrage: hast Du mal über einen längeren Zeitraum geschaut, in welchen Abständen der Adapter bei Dir den Heartbeat sendet?

Die Protokolle sollten eigentlich der Fehlersuche dienen. Wenn ich einfach gesagt hätte: "geht nicht, bitte ändern", wäre das wohl nicht hilfreich..

Das es bei Dir läuft, freut mich für Dich. Vielleicht sehen es die anderen Gateways ja auch nicht ganz so eng mit dem Timeout. und halten die Tunnel länger offen. Das das Wiregate ein instabiles Gateway ist möchte ich so eigentlich nicht so stehen lassen. Ich hatte den Fehler ja anfangs nicht nur beim Adapter gesucht und daher meine Frage parallel auch beim Hersteller des Wiregates platziert, wo mir auch freundlich geholfen wurde. Von Seiten Wiregate wurde wie ich mittlerweile weiß bereits vor einiger Zeit das Problem festgestellt und die Programmierer haben das Problem analysiert und sind genau zum gleichen Ergebnis gekommen, wie ich. Das Problem wurde wohl auch an ioBroker adressiert. Von daher ist meine Analyse wohl nicht ganz unbegründet.

Zu Deinem letzten Satz möchte ich nur sagen, dass ich da scheinbar etwas falsch verstanden habe. Ich dachte Github ist in diesem Kontext zum melden und gemeinsamen analysieren von Fehlern gedacht. Hierbei sind Logs von Fehlern eigentlich ganz hilfreich. Wenn ich da bei der Fehlersuche zu penetrant hilfreich sein wollte, werde ich versuchen mich zu "bessern"...

**Comment by MiCon72** [comment]
Ich bin die letzten Tage die ganzen Versionen mal durchgegangen. Den Fehler gibt es seit Version 1.0.35, die Version 1.0.34 läuft noch ordnungsgemäß. Im Changelog zur Version 1.0.35 steht: fixed permanent reconnects, if no traffic on knx-bus Ich vermute, dass sich hierbei der Fehler eingeschlichen hat.

**Comment by MiCon72** [comment]
Ich habe zur Sicherheit auch noch einmal den Netzwerkverkehr mitgeschnitten und mit Wireshark analysiert. Der Mitschnitt erfolgte direkt auf dem ioBroker Server, welcher mittlerweile auf einem Intel Nuc direkt unter Debian installiert ist. Der Mitschnitt hat meine bisherige Analyse ebenfalls bestätigt. Der ioBroker sendet die Connectionstaterequests an das Gateway und das Gateway antwortet mit einem Connectionstateresponse. Leider kommen die Connectionstaterequests vom ioBroker nicht immer innerhalb der vorgeschriebenen 120 Sekunden. In diesen Fällen kommt vom Gateway wie bereits beschrieben die negative Quittung und der Adapter baut den Tunnel neu auf.

**Comment by MiCon72** [comment]
Bei mir läuft es jetzt. Ich habe einen "Proxy" mit knxd dazwischengeschaltet. Dort hatte ich die gleichen Abbrüche aus oben dargestellten Gründen. Ich habe im Source-Code von knxd dann aber den Timeout von 120 Sekunden (KNX-Spezifikation) auf 240 Sekunden erhöht. Das ist zwar nicht mehr KNX-konform aber damit läuft der Adapter jetzt ohne Probleme. 

Vielen Dank an Chefkoch für seine super Arbeit und den ansonsten tollen Adapter. Vielleicht findet er ja mal die Zeit, den Timeout des Adapters etwas zu verkürzen (knxd sendet im Standard übrigens alle 30 Sekunden einen heartbeat). 

Liebe Grüße

Michael

**Comment by trollvottel** [comment]
Ich reihe mich mal ein in die Liste betroffener User mit Verbindungsabbrüchen. Bis vor kurzem lief der Adapter noch, inzwischen bleibt er auf gelb und loggt nur noch ständig 
`knx.0 | 2021-05-07 10:49:00.564 | info | (7588) Connected  - local UDP Server listening on 192.168.0.131:47234
-- | -- | -- | --
knx.0 | 2021-05-07 10:49:00.561 | info | (7588) Using UDP with local IP: 192.168.0.131
knx.0 | 2021-05-07 10:48:58.560 | info | (7588)  STATE_NOT_CONNECTED : Try to connect / reconnect :  STATE_CONNECT_REQUEST(3) to STATE_NOT_CONNECTED(0).`

**Comment by Sirfauntleroy** [comment]
Auch ich muss mich hier leider einreihen.
Bei mit treten die Timeouts ebenfalls auf. Meist im Abstand von etwa 2 Minuten, manchmal aber auch 10 Minuten nicht!
Getestet habe ich mitlerweile 3 Schnittstellen. 
Das MDT-IP-Gateway
Gira IP-Router 
und Weinzierl 731 (Wobei das Weinzierl wohl von allem am stabilsten läuft...)

**Comment by trollvottel** [comment]
Bei mir war es bereits nach wenigen Sekunden. Habe dann aber rausgefunden, dass das Ändern der Netzwerkschnittstelle Abhilfe bringt. Warum auch immer? Mit dem VLAN-Interface (ganz anderes VLAN, nichtmal das KNX) verbindet der Adapter wieder erfolgreich. Zuvor klappte es auch mit eth0, nun nicht mehr.
