### ISSUE TITLE
KNX reconnect

### ISSUE THREAD

**Issue by obodeldog** [ioBroker/ioBroker.knx#58]
Since the newest version there are less reconnects per day (see the bar on the right of the screenshot). But it still happens. It seems to me that these always come when several events have occurred before. Exactly I could not reproduce it however. Yesterday, for example, the front door opened, but didn't close any more, because then about 2 minutes no KNX commands arrive anymore. Only then comes a reconnect and it works again. In the following a LOG in which "somewhere" the error occurs.
![image](https://user-images.githubusercontent.com/35403739/57198167-f42aa800-6f6f-11e9-8468-9ab305f7bd59.png)

[https://bit.ly/2JkfNIf](url)

**Comment by Garfonso** [comment]
I have a similar issue here.
I always have a disconnect/reconnect when a certain devices sends a status message.

**Comment by chefkoch009** [comment]
Hallo,
I think I found the reason for reconnect. I recognized that this occurs if something is written to a device wich doesn‘t exist or did Not answer.  then the Adapter tries to get the connection state, but recieves a message that did not match the previous flow. And after this comes the reconnect.

Can you check this to verify this behaviour?

**Comment by Garfonso** [comment]
Hi, 

I attached a log, in the first lines there is the output from the bus monitor from ETS5. As you can see I switch the GA on and off after a few seconds using ETS (but the same happens if I control the device from another source, even from ioBroker itself). 
The reconnect happens before the first status response. I must admit I did never see the Broadcast thing bevore. Don't know what that is or why the device does it... but ioBroker does not recognize that the devices got switched off, because of the reconnect and it happens every time the devices is used.

[knx.log](https://github.com/ioBroker/ioBroker.knx/files/3414020/knx.log)

**Comment by chefkoch009** [comment]
changed reconnect behaviour. Please update this issue if it not works. 
If it works, please close this issue.

**Comment by peer69** [comment]
New version gives me a lot of disconnects (about every 4 minutes). Did not have this issue before at all.

**Comment by boellner** [comment]
possibly same as #184
